### ISSUE TITLE
Favorite button visual indication of click

### ISSUE THREAD

**Issue by MandyAlford** [MandyAlford/vrad-frontend#19]
I think it would be great if our favorite buttons showed the user they've been clicked. (Currently you have to look at the favorites button counter in the header for any indication the listing has been added). A button color change or quick message indicating the listing has been favorited would make for a much better UX. (and prevent multiple clicks from a confused user).

**Comment by CLPena** [comment]
Yes! Great idea. I'll take a look at the logic and see where I can put this in most seamlessly.

**Comment by CLPena** [comment]
Fixed this and made it so it persists as the user navigates away and back to the favorited listing. Let me know what you think!

**Comment by MandyAlford** [comment]
This is great. Thanks! Will merge now.
